StylesPath = .github/styles
MinAlertLevel = suggestion

[docs/**/*.{md,rst}]
# Only apply Vale to the docs/ folder
BasedOnStyles = Mesa
Mesa.Branding = error

# --- DISABLE RULES ---
Vale.Spelling = NO # Disable Spelling (MESA uses codespell)
