"""Mesa Data Collection Module.

DataCollector provides a standardized way to collect data generated by a Mesa model.
It supports model-level, agent-level, agent-type-level data, and custom tables.

Example Usage:
    from mesa import Model
    from mesa.datacollection import DataCollector

    class MyModel(Model):
        def __init__(self):
            self.agents = []
            self.datacollector = DataCollector(
                model_reporters={
                    "AgentCount": lambda m: len(m.agents)
                },
                agent_reporters={
                    "Energy": "energy"
                }
            )

        def step(self):
            self.datacollector.collect(self)

    model = MyModel()
    for _ in range(10):
        model.step()

    model_df = model.datacollector.get_model_vars_dataframe()
    agent_df = model.datacollector.get_agent_vars_dataframe()

Common Errors:
    - Using a non-existent attribute in reporters → AttributeError
    - Incorrect reporter format → must be [function, [params]]
    - Adding rows to undefined tables → TableMissingException

Performance Notes:
    - Attribute access is faster than lambda functions for large simulations.
    - deepcopy is avoided for immutable types to improve performance.
"""

import contextlib
import types
from copy import deepcopy
from functools import partial

with contextlib.suppress(ImportError):
    pass


class DataCollector:
    """Class for collecting data generated by a Mesa model.

    A DataCollector collects model-level, agent-level, and agent-type-level
    data at each simulation step. Reporters can be defined using attribute
    names, functions, methods, or parameterized callables.
    """

    def __init__(
        self,
        model_reporters=None,
        agent_reporters=None,
        agenttype_reporters=None,
        tables=None,
    ):
        """Instantiate a DataCollector.

        Args:
            model_reporters (dict, optional):
                Mapping of variable names to attributes/functions.

            agent_reporters (dict, optional):
                Mapping of variable names to attributes/functions.

            agenttype_reporters (dict, optional):
                Mapping of agent types to reporter dictionaries.

            tables (dict, optional):
                Mapping of table names to column lists.

        Notes:
            - Avoid lambda functions if you need to pickle your model.
            - Attribute access is faster than function calls for large simulations.
        """
        self.model_reporters = {}
        self.agent_reporters = {}
        self.agenttype_reporters = {}

        self.model_vars = {}
        self._collection_steps = []
        self._agent_records = {}
        self._agenttype_records = {}
        self.tables = {}

        self._validated = False

        if model_reporters is not None:
            for name, reporter in model_reporters.items():
                self._new_model_reporter(name, reporter)

        if agent_reporters is not None:
            for name, reporter in agent_reporters.items():
                self._new_agent_reporter(name, reporter)

        if agenttype_reporters is not None:
            for agent_type, reporters in agenttype_reporters.items():
                for name, reporter in reporters.items():
                    self._new_agenttype_reporter(agent_type, name, reporter)

        if tables is not None:
            for name, columns in tables.items():
                self._new_table(name, columns)

    def collect(self, model):
        """Collect all the data for the given model object."""
        if self.model_reporters:
            if hasattr(self, "_collection_steps"):
                self._collection_steps.append(model.time)

            for var, reporter in self.model_reporters.items():
                if isinstance(reporter, (types.LambdaType, partial)):  # ✅ FIXED
                    self.model_vars[var].append(deepcopy(reporter(model)))
                elif isinstance(reporter, str):
                    self.model_vars[var].append(
                        deepcopy(getattr(model, reporter, None))
                    )
                elif isinstance(reporter, list):
                    self.model_vars[var].append(deepcopy(reporter[0](*reporter[1])))
                else:
                    self.model_vars[var].append(deepcopy(reporter()))

        if self.agent_reporters:
            agent_records = self._record_agents(model)
            self._agent_records[model.time] = list(agent_records)

        if self.agenttype_reporters:
            self._agenttype_records[model.time] = {}
            for agent_type in self.agenttype_reporters:
                agenttype_records = self._record_agenttype(model, agent_type)
                self._agenttype_records[model.time][agent_type] = list(
                    agenttype_records
                )
