name: Performance benchmarks

on:
  workflow_run:
    workflows: [Performance benchmarks]
    types: 
      - completed

jobs:
  comment_pr:
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/artifacts
      - name: 'Unzip artifact'
        run: |
          unzip "${{ runner.temp }}/artifacts/pr_number.zip" -d "${{ runner.temp }}/artifacts"
          unzip "${{ runner.temp }}/artifacts/timing.zip" -d "${{ runner.temp }}/artifacts"
      - name: Comment PR
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const temp = '${{ runner.temp }}/artifacts';
            const output = fs.readFileSync(path.join(temp, 'timing'), 'utf8');
            output = Buffer.from(output, 'base64').toString('utf8');
            const issue_number = Number(fs.readFileSync(path.join(temp, 'pr_number'));
            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Performance benchmarks:\n\n' + output
            });
